# Added config file (now required)  see:
# https://docs.readthedocs.io/en/stable/config-file/index.html

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
sphinx:
  configuration: docs/conf.py